Enable IPC module tests
treitter/vehicle_signal_manager pull request #6
Opened 2017-05-25 23:30 UTC by araujol

This commit enables the tests for the IPC ZeroMQ module.

Signed-off-by: Luis Araujo <luis.araujo@collabora.co.uk>

2017-05-26 23:59 UTC, treitter requested changes
Generally looks good; I'd just like a few minor changes.

2017-05-26 23:59 UTC, treitter commented on tests.py
> +            # Read state dump from log file vsm.log
cut off the trailing " vsm.log" in this comment so you don't alias the content of VSM_LOG_FILE

2017-05-26 23:59 UTC, treitter commented on tests.py
> +VSM_LOG_FILE = 'vsm.log'
I think we should use a non-default file (like vsm-tests.log) so we don't potentially overwrite an existing file from a previous (manual) run.

2017-05-26 23:59 UTC, treitter commented on tests.py
> +        if TestVSM.ipc_module != 'zeromq':
Assuming we're using a non-default log file in `VSM_LOG_FILE` above, specify it here in case `TestVSM.ipc_module == 'zeromq'`

2017-05-27 00:56 UTC, araujol commented
Ok, I applied the suggested changes.

I also changed **self.ipc_module** to **TestVSM.ipc_module** , since it can show better it is a class variable.

2017-05-30 15:43 UTC, merged